spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
    password: password
    url: jdbc:mysql://localhost:3306/BanqueDB
    username: root
  jpa:
    show-sql: true
#  main:
#    banner-mode: "off"
  banner:
    location: banner.txt

